name: CI/CD Pipeline

on:
  push:
    branches:
      - dev # Run tests/builds on dev branch
      - main # Deploy only when code hits main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests for dev branch..."
          # put your test/build commands here (npm test, pytest, etc.)

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Apache
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /var/www/akhils.site/public_html || exit 1
            git reset --hard origin/main
            git pull origin main
            sudo chown -R www-data:www-data .
            sudo chmod -R 755 .
            sudo systemctl reload apache2
          EOF
