name: Deploy to DigitalOcean Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Apache server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /var/www/akhils.site/public_html || exit 1
            git pull origin main
            sudo chown -R www-data:www-data .
            sudo chmod -R 755 .
            sudo systemctl reload apache2
          EOF
